### ISSUE TITLE
Server Crash upon startup (NoClassDefFoundError)

### ISSUE THREAD

**Issue by aking4125** [vfyjxf/NotEnoughEnergistics#10]
Hey,

We've tried out your mod and we're getting the following crash report. Removing this mod and switching back to Just Enough Energistics allows the server to continue normally

[crash-2021-09-18_07.52.31-server.txt](https://github.com/vfyjxf/NotEnoughEnergistics/files/7189838/crash-2021-09-18_07.52.31-server.txt)

Here is the debug.log if anything:

[debug-4.log](https://github.com/vfyjxf/NotEnoughEnergistics/files/7189839/debug-4.log)

Within the logs and crash report, it doesn't really mention this mod, but it did mention AE2, removing that and all the addons we had worked on. So I then reinstalled each AE2 addon one at a time and this was the cause of the crash for some reason. There could be some type of conflict somewhere. But Just Enough Energistics works perfectly fine replacing this.

**Comment by vfyjxf** [comment]
Will be fixed in the next version
