### ISSUE TITLE
无法在无线合成终端中请求合成缺失材料

### ISSUE THREAD

**Issue by MikuMiddo** [vfyjxf/NotEnoughEnergistics#13]
使用_AE2 Wireless Crafting Terminal_的无线合成终端中请求缺失材料[ctrl+鼠标左击]时，会导致合成框中遗留下合成表下方三格位置的物品残影，重新打开终端后消失

![image](https://user-images.githubusercontent.com/53809752/136905096-5ff39fb9-953a-4e42-aead-deb1974bde65.png)

![image](https://user-images.githubusercontent.com/53809752/136905142-a62a4ac5-dd43-40cc-aeb3-1c4223a25f12.png)

**Comment by vfyjxf** [comment]
这个是我还没做无线合成终端的兼容，下个版本修复

**Comment by vfyjxf** [comment]
已在最新版本修复
