### ISSUE TITLE
Crafting Tree construction failed (and broken recipes ic2)

### ISSUE THREAD

**Issue by BlayzerQ** [vfyjxf/NotEnoughEnergistics#17]
Versions of mods:
NotEnoughItems-1.7.10-2.1.12-GTNH-universal
NotEnoughEnergistics-1.7.10-1.3.0
appliedenergistics2-rv3-beta-6
industrialcraft-2-2.2.827-experimental

When i create pattern by "?" button in terminal, some items from IC2 (example - Transformator upgrade) will broken (meta: 32767)

![image](https://user-images.githubusercontent.com/10747701/139747945-1baa1f2d-a28d-4bfe-90b2-267ad741f40d.png)

Demonstration (video): https://ufile.io/wpfxh1vo

![image](https://user-images.githubusercontent.com/10747701/139747687-10fbc42d-e747-409c-94e6-e9d817407178.png)

Call craft item from pattern return error in chat: 
Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Crafting Tree construction failed.

**Comment by vfyjxf** [comment]
Can you tell me how to reproduce it, I remember that nee did not modify the input ingredients

> Versions of mods: NotEnoughItems-1.7.10-2.1.12-GTNH-universal NotEnoughEnergistics-1.7.10-1.3.0 appliedenergistics2-rv3-beta-6 industrialcraft-2-2.2.827-experimental
> 
> When i create pattern by "?" button in terminal, some items from IC2 (example - Transformator upgrade) will broken (meta: 32767)
> 
> ![image](https://user-images.githubusercontent.com/10747701/139747945-1baa1f2d-a28d-4bfe-90b2-267ad741f40d.png)
> 
> Demonstration (video): https://ufile.io/wpfxh1vo
> 
> ![image](https://user-images.githubusercontent.com/10747701/139747687-10fbc42d-e747-409c-94e6-e9d817407178.png)
> 
> Call craft item from pattern return error in chat: Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Crafting Tree construction failed.

**Comment by vfyjxf** [comment]
Also, can you provide the game log, I need the game log

**Comment by BlayzerQ** [comment]
To reproduce it - click to ? button on IC2 items (transformator module - for example) and get :32767 meta on some items. After it - many IC2 crafts in NEI has :32767 meta. 
Demonstration (video): https://ufile.io/wpfxh1vo

**Comment by BlayzerQ** [comment]
> Also, can you provide the game log, I need the game log

Server or client?

**Comment by vfyjxf** [comment]
> > Also, can you provide the game log, I need the game log
> 
> Server or client?

client

**Comment by vfyjxf** [comment]
After a period of debugging, I found that this is a gtnh nei problem. I can only make nee fill the correct recipe, but I can't make nei show the correct recipe
