### ISSUE TITLE
[1.7.10] Something goes wrong

### ISSUE THREAD

**Issue by DevTimur** [vfyjxf/NotEnoughEnergistics#18]
in "NotEnoughEnergistics-1.7.10-1.2.19.jar" you did something wierd, now i can't launch any version higher
then "NotEnoughEnergistics-1.7.10-1.2.16.jar"

I get this **[CRASH](https://pastebin.com/iRBqYKxV)** every time

**Comment by vfyjxf** [comment]
Will be fixed in the next version
