### ISSUE TITLE
Rendering highlight causes severe lag when mouse is over "?" button

### ISSUE THREAD

**Issue by vfyjxf** [vfyjxf/NotEnoughEnergistics#22]

**Comment by dbrafael** [comment]
This and [https://github.com/vfyjxf/NotEnoughEnergistics/issues/28](url) has been happening to me on 2.0.2. The lag starts happening after some time playing, maybe related to encoding recipes. Every time I hover over an item/the "?" button I get a small freeze. The freeze gets worse as time goes on.

**Comment by vfyjxf** [comment]
> This and [https://github.com/vfyjxf/NotEnoughEnergistics/issues/28](url) has been happening to me on 2.0.2. The lag starts happening after some time playing, maybe related to encoding recipes. Every time I hover over an item/the "?" button I get a small freeze. The freeze gets worse as time goes on.


This may be related to the feature from pae2, I made some optimizations at https://github.com/vfyjxf/NotEnoughEnergistics/releases/tag/2.0.3-hotfix but I'm not sure whether it works.

**Comment by dbrafael** [comment]
I have not had this happen to me again on 2.0.3-hotfix
