### ISSUE TITLE
在服务器中使用 [?] 写入样板时发生崩溃

### ISSUE THREAD

**Issue by GwenLunbing** [vfyjxf/NotEnoughEnergistics#25]
服务器客户端均已安装mod，崩溃报告：https://pastebin.ubuntu.com/p/hYkxyQ7j6Z/
而比较神奇的事情是：如果在客户端内使用1.4.0版本，在服务器安装1.4.1版本就能正常使用。
（尽管1.4.1修复了1.4.0在服务器内无法使用的bug）

**Comment by vfyjxf** [comment]
这个问题是因为gtnh版本的nei做了一些改动，然后我错误的修改导致老版本的nei和官方版本的nei兼容失效的问题。

**Comment by vfyjxf** [comment]
修复版本我会在等下传到curseforge
