### ISSUE TITLE
[CRASH] Updating screen events

### ISSUE THREAD

**Issue by Speecker** [vfyjxf/NotEnoughEnergistics#26]
I ran into a problem causing a crash when trying to make a new pattern for Coal Dust by EnderIO in their SAG Mill but upon clicking next page in JEI while doing so the game crashes.

See the Crash-Report for further details :)

https://pastebin.com/nWgwXhHk

**Comment by vfyjxf** [comment]
> I ran into a problem causing a crash when trying to make a new pattern for Coal Dust by EnderIO in their SAG Mill but upon clicking next page in JEI while doing so the game crashes.
> 
> See the Crash-Report for further details :)
> 
> https://pastebin.com/nWgwXhHk

fix in1.12.2-1.2.4
