### ISSUE TITLE
mod功能偶尔会失效，而且在jei查看部分物品配方时会出现长时间卡顿

### ISSUE THREAD

**Issue by HDGzzz** [vfyjxf/NotEnoughEnergistics#27]
e2e整合包加入了NEE,第一次可以正常使用，第二次不知道为何就失效了，模组设定里能看到NEE也可以配置，重进存档无法解决，但重进游戏就恢复正常了，但第三次时又失效了。而且在合成终端上查看部分配方时会卡住很长时间

**Comment by vfyjxf** [comment]
> e2e整合包加入了NEE,第一次可以正常使用，第二次不知道为何就失效了，模组设定里能看到NEE也可以配置，重进存档无法解决，但重进游戏就恢复正常了，但第三次时又失效了。而且在合成终端上查看部分配方时会卡住很长时间

NEE版本是最新的1.2.4吗

**Comment by HDGzzz** [comment]
是1.2.4版本，正在重启minecraft，稍后才能举例是哪些物品

**Comment by HDGzzz** [comment]
> 

基本上所有的物品都有一定卡顿，部分物品卡顿很小到几乎能无视，但部分有矿词合成的物品如书架，各种用木板合成的物品，木棍合成的物品等等，点开都会卡上十几秒，是未响应那样的卡住

**Comment by vfyjxf** [comment]
> 

是在终端内打开的配方界面吗，还是说任何地方都会发生卡顿

**Comment by HDGzzz** [comment]
在合成终端查看配方就会卡顿，其他地方都没有卡顿

**Comment by vfyjxf** [comment]
这个原因貌似是在合成终端内我会获取ae里面的物品然后查询当前配方缺失的物品，网络里面物品过多的话貌似就会造成性能问题

**Comment by HDGzzz** [comment]
样板终端也会卡顿

**Comment by HDGzzz** [comment]
我试了一下把存储元件都拿出来，只留一个64k元件还是会卡顿很长时间

**Comment by HDGzzz** [comment]
甚至不放存储元件查看木板参与的合成都会卡顿10s左右

**Comment by vfyjxf** [comment]
> 甚至不放存储元件查看木板参与的合成都会卡顿10s左右
尝试一下这个修复版本，由于我并无法复现，所以只能看你的测试了(注意需要解压)
[NotEnoughEnergistics-1.12.2-1.2.5.zip](https://github.com/vfyjxf/NotEnoughEnergistics/files/8419573/NotEnoughEnergistics-1.12.2-1.2.5.zip)

**Comment by vfyjxf** [comment]
> > > 甚至不放存储元件查看木板参与的合成都会卡顿10s左右
> > 
> > 
> > 尝试一下这个修复版本，由于我并无法复现，所以只能看你的测试了(注意需要解压) [NotEnoughEnergistics-1.12.2-1.2.5.zip](https://github.com/vfyjxf/NotEnoughEnergistics/files/8419573/NotEnoughEnergistics-1.12.2-1.2.5.zip)
> 
> 卡顿问题仍未解决

我尝试复现了一些，貌似是因为我匹配的逻辑造成的，之后我看看能不解决

**Comment by HDGzzz** [comment]
1.2.5版本有个新问题，根据配方来自动切换终端模式 功能失效了

**Comment by vfyjxf** [comment]
在NEE2.0中被修复。
