### ISSUE TITLE
Crash when placing cables when NEE 2.0.0

### ISSUE THREAD

**Issue by ghost** [vfyjxf/NotEnoughEnergistics#34]
**Describe the bug**
Crash when placing cables

**To Reproduce**
Place any kind of ME cables

**Expected behavior**
No crash

**Additional context**
[crash-2022-11-27_13.26.03-client.txt](https://github.com/PrototypeTrousers/Applied-Energistics-2/files/10097594/crash-2022-11-27_13.26.03-client.txt)

**Environment**
In pure pae2 environment,it's fine.

- Minecraft Version: 
- AE2 Version: appliedenergistics2-rv6-stable-7-extended_life-v0.54.15
- NEE Version: NotEnoughEnergistics-1.12.2-2.0.0
- Forge Version: 14.23.5.2860

https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/191

**Comment by vfyjxf** [comment]
This is a problem caused by nee's asm, I will release a version with pae2 support later

**Comment by vfyjxf** [comment]
fix in 2.0.1
