### ISSUE TITLE
1.12.2的NEE在合成终端打开Ender IO的磨粉机jei会崩客户端

### ISSUE THREAD

**Issue by 200542053** [vfyjxf/NotEnoughEnergistics#41]
直接在JEI里打开没事，在合成终端里打开Ender IO的磨粉机的jei就会崩客户端。

![QQ图片20230228012008](https://user-images.githubusercontent.com/52939604/221634664-6214cfdd-8e4b-457f-8254-012a7233b289.jpg)
[crash-2023-02-27_23.37.09-client.txt](https://github.com/vfyjxf/NotEnoughEnergistics/files/10842284/crash-2023-02-27_23.37.09-client.txt)

Not Enough Energistics版本：1.12.2-2.0.3
AE2版本：appliedenergistics2-rv6-stable-7-extended_life-v0.55.8
Ender IO版本：5.3.70
JEI版本：4.16.1.1001
Forge版本：14.23.5.2860

**Comment by Coloryr** [comment]
估计是其他mod的问题，我测试无问题

**Comment by vfyjxf** [comment]
> 估计是其他mod的问题，我测试无问题

其实是eio用null代替了ItemStack.EMPTY, mee默认itemstack是非null的，之前也出过这个问题，我重写的时候又忘了处理null值了

**Comment by Coloryr** [comment]
> > 估计是其他mod的问题，我测试无问题
> 
> 其实是eio用null代替了ItemStack.EMPTY, mee默认itemstack是非null的，之前也出过这个问题，我重写的时候又忘了处理null值了

所以不合并了？
