### ISSUE TITLE
EIO的SAG磨粉机中带磨珠的配方崩溃

### ISSUE THREAD

**Issue by HakureiNyaruko** [vfyjxf/NotEnoughEnergistics#57]
写样板时Shift转移SAG磨粉机中带磨珠的配方会崩溃（没有磨珠的配方可以正常写进样板）
游戏版本：1.12.2，NEE版本：2.0.7
[crash-2024-05-23_22.09.31-client.txt](https://github.com/vfyjxf/NotEnoughEnergistics/files/15418123/crash-2024-05-23_22.09.31-client.txt)

**Comment by koaker** [comment]
1.12.2的重写版本的nee版本已经有2.0.9了，作者未编译成可执行的jar包，需要你自己编译

**Comment by HakureiNyaruko** [comment]
Solved
