### ISSUE TITLE
在 GTNH 中无法使用

### ISSUE THREAD

**Issue by LasmGratel** [vfyjxf/NotEnoughEnergistics#9]
NEI 版本为 NotEnoughItems-1.7.10-2.1.6-GTNH-universal.jar
在样板终端中 Shift+? 不会更改当前样板内容

**Comment by vfyjxf** [comment]
如果加入了服务器，请确保服务端也有对应的mod，填物品到终端是由服务端执行的，因为我不知道该怎么从客户端填一个玩家身上不存在的物品
